[colors.primary]
background = '#24273a'
foreground = '#cad3f5'

[colors.selection]
text = '#cad3f5'
background = '#243e72'

[colors.cursor]
text = '#24273a'
cursor = '#8aadf4'

[colors.normal]
black   = '#1e2030'
red     = '#ff7299'
green   = '#7af48c'
yellow  = '#fff872'
blue    = '#6e96e7'
magenta = '#163470'
cyan    = '#8aadf4'
white   = '#eff4ff'

[colors.bright]
black   = '#92969e'
red     = '#ff9fba'
green   = '#a5ffb3'
yellow  = '#fffaa5'
blue    = '#a0bfff'
magenta = '#b1cbff'
cyan    = '#cdddff'
white   = '#f8faff'
